name: NBwar
version: @version@
description: A PVP plugin for minecraft 1.12.2
main: io.github.wonjongin.nbwar.NBwar
softdepend: [HolographicDisplays]

commands:
  n:
    description: Command of NBwar! Type /n